GET http://localhost:3000/todo/?status=TO%20DO



###

GET http://localhost:3000/todo/?priority=HIGH


###

GET http://localhost:3000/todo/?priority=HIGH&status=IN%20PROGRESS

###

GET http://localhost:3000/todo/?search_q=Play


###

GET http://localhost:3000/todo/10/

###
POST http://localhost:3000/todo/
Content-Type:application/json


   {
        "id": 1,
        "todo": "Watch Movie",
        "priority": "LOW",
        "status": "TO DO"
      }

###


PUT http://localhost:3000/todo/10
Content-Type:application/json

{
      "priority": "HIGH"
    }
    


###

DELETE http://localhost:3000/todo/1